version: "3.8"
services:
  api:
    build: ./server
    container_name: api_c
    ports:
      - "5000:5000"
  squadron:
    build: .
    container_name: squadron_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
